Updated github link for iam policy
The Link for github was hard-coded to 1.14. With the new version it will miss waf2 policies.

This PR Avoid this error:

AccessDeniedException: User: arn:aws:sts::xxxxxxx:assumed-role/role0001/yyyyyy is not authorized to perform: wafv2:GetWebACLForResource on resource: arn:aws:wafv2:us-east-1:xxxxxx:regional/webacl